package de.eso.bytebuddy;

public enum EventType {
  CLASS_FOR_NAME,
  CLASS_NEW_INSTANCE,
  CLASS_GET_DECLARED_METHODS,
  CLASS_GET_FIELDS,
  CLASS_GET_METHODS,
  CLASS_GET_DECLARED_FIELDS,
  CLASS_GET_METHOD,
  CLASS_GET_DECLARED_METHOD,
  CLASS_GET_FIELD,
  CLASS_GET_DECLARED_FIELD,
  CLASS_GET_CONSTRUCTORS
}
